---
abstract: 'form html generator/validator'
author:
  - 'Tokuhiro Matsuno <tokuhirom  slkjfd gmail.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Shakan
no_index:
  directory:
    - inc
    - t
recommends:
  Lingua::JA::Regular::Unicode: 0
requires:
  Any::Moose: 0.05
  Filter::Util::Call: 0
  FormValidator::Lite: 0.02
  List::MoreUtils: 0.22
  Mouse: 0.19
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_01
